[package]
name = "pfg"
version = "0.1.0"
edition = "2021"
description = "pp_features mask generator for AMDGPU"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
